pipe:
  path_root: "payload"
  transform:
    strip:
      - "id"
      - "numero-registro"
      - "situacao"
      - "denominacao"
      - "titulo"
      - "autor"
      - "classificacao"
      - "resumo-descritivo"
      - "url"
    lowercase:
      - "url"
    split:
      classificacao:
        - ">"
        - "&gt;"
    capitalize:
      - "classificacao"
    add_hash:
      - target: "fingerprint"
        method: "md5"
        fields:
          id: null
          museu: null
          "numero-registro": null
      - target: "hash-content"
        method: "md5"
        fields:
          "id": null
          "resumo-descritivo": null
          "titulo": null
          "numero-registro": null
          "situacao": null
          "denominacao": null
          "autor": null
          "classificacao": null
          "museu": null
          "url": null
  target_collection:
    connection_name: "treinamento.local"
    collection_id: "6"
    metadata_identifier: "58" # metadado no agregador que guarda o identificador unico dos itens no processo de agregação
    metadata_hash_content: "55" #metadado no agregador que guarda o hash do conteudo dos itens no processo de agregação 
    ignore_items_without_identifier: true # ignorar o item caso não tenha o metadado identificador 
    metadata:
      "19": "id"
      "11": "resumo-descritivo"
      "9": "titulo"
      "25": "numero-registro"
      "28": "situacao"
      "33": "denominacao"
      "37": "autor"
      "42": "classificacao"
      "48": "museu"
      "58": "fingerprint"
      "52": "url"
      "55": "hash-content"
      "_thumbnail": "thumbnail"
      "_document": "document"
